parameters:
#    tutei_forms.example.class: Tutei\FormsBundle\Example

services:
#    tutei_forms.example:
#        class: %tutei_forms.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
